### ISSUE TITLE
Can't disable QuoteFix for a single reply

### ISSUE THREAD

**Issue by dsedivec** [robertklep/quotefixformac#57] opened 2015-12-26 22:27 UTC
Hi!  I just upgraded from Mavericks to El Capitan and I can no longer hold the option key when replying to a message to disable QuoteFix.  OS X 10.11.2, Mail.app 9.2, QuoteFix 2.7.2

Steps to reproduce:

1. Press cmd-option-r to reply to a message

Expected behavior: QuoteFix does not trim the data after the signature separator, does not move cursor to bottom—i.e. QuoteFix is disabled for this reply.

Observed behavior: QuoteFix does everything it normally does to a message, as if I wasn't holding the option key.

Here's what I see in Console.app when I turn on "Debugging" in QuoteFix's preferences and then hit cmd-option-r in Mail.app:

```
12/26/15 16:07:09.082 Mail[6515]: [ComposeViewController finishLoadingEditor]
12/26/15 16:07:09.091 Mail[6515]: QuoteFix is not active, so no QuoteFixing for you!
12/26/15 16:07:09.104 Mail[6515]: [ComposeViewController finishLoadingEditor]
12/26/15 16:07:09.166 Mail[6515]: calling remove_old_signature()
12/26/15 16:07:09.173 Mail[6515]: calling move_above_new_signature()
12/26/15 16:07:09.174 Mail[6515]: calling cleanup_layout()
12/26/15 16:07:09.174 Mail[6515]: calling view.moveToBeginningOfLine()
12/26/15 16:07:09.175 Mail[6515]: QuoteFixing done
12/26/15 16:07:09.669 Mail[6515]: [ComposeViewController show]
```

For reference, here's what the logs look like when I just do a normal cmd-r reply, no option key down:

```
12/26/15 16:25:29.101 Mail[6611]: [ComposeViewController finishLoadingEditor]
12/26/15 16:25:29.132 Mail[6611]: message type "5" not in [1, 8, 2, 3], not quotefixing
12/26/15 16:25:29.132 Mail[6611]: calling view.moveToBeginningOfLine()
12/26/15 16:25:29.132 Mail[6611]: QuoteFixing done
12/26/15 16:25:29.146 Mail[6611]: [ComposeViewController finishLoadingEditor]
12/26/15 16:25:29.208 Mail[6611]: calling remove_old_signature()
12/26/15 16:25:29.215 Mail[6611]: calling move_above_new_signature()
12/26/15 16:25:29.216 Mail[6611]: calling cleanup_layout()
12/26/15 16:25:29.217 Mail[6611]: calling view.moveToBeginningOfLine()
12/26/15 16:25:29.217 Mail[6611]: QuoteFixing done
12/26/15 16:25:29.691 Mail[6611]: [ComposeViewController show]
```

Any idea how I can get back the "hold option to disable QuoteFix for a single message" behavior?  Thank you!

In case it matters, I am using an Apple Bluetooth keyboard on my MacBook Pro, and I have the command and option modifier keys swapped.  I tried swapping them back on both keyboards, no difference in QuoteFix behavior (only tested with Bluetooth keyboard).  I also tried using the MBP keyboard (with modifiers swapped) as well as the Bluetooth keyboard (with modifiers swapped).

**Comment by robertklep** [comment] 2015-12-26 22:30
Looks that this feature is broken on El Capitan, it doesn't work for me either (on a MBP). I'll take a look ASAP 🙂

**Comment by dsedivec** [comment] 2015-12-26 23:37
> Looks that this feature is broken on El Capitan, it doesn't work for me either (on a MBP). I'll take a look ASAP 🙂

Awesome, thank you very much!

I was waiting to open a new issue for this, but if you're going to be in there looking at this code already, you might also be interested to know that I also used to be able to hit cmd-shift-opt-f to forward with QuoteFix disabled, but in El Capitan cmd-shift-opt-f doesn't do anything as far as I can see, not even starting a new forward.  This differs from the reply behavior, where the reply is started but QuoteFix remains enabled regardless of the option modifier.

To reiterate:
* Cmd-r: replies to message, works as expected
* Cmd-opt-r: replies to message, disables QuoteFix, but not currently working (my original issue)
* Cmd-shift-f: forwards message, works as expected
* Cmd-shift-opt-f: forwards message, disables QuoteFix, but currently does nothing at all, not even starting a new forward

**Comment by robertklep** [comment] 2015-12-27 11:17
I _somewhat_ managed to fixed replies in [v2.7.3](https://github.com/robertklep/quotefixformac/releases/tag/v2.7.3).

The issue is that there's a race condition between pressing down the `Opt` key and the actual quotefixing process starting, thanks to all those great window animations on ElCap.

You have to keep pressing down the `Opt` key until the entire process has finished, otherwise you may end up with a half-quotefixed message (where the message has been fixed, but the cursor hasn't been placed properly, or the other way around).

It's the best I can do for now, as I have yet to figure out exactly how those pesky animations work.

**Comment by dsedivec** [comment] 2015-12-27 18:25
This is great, thanks Robert.  2.7.3 tested working here.  I can even temporarily disable QuoteFix by hitting cmd-shift-f to start a forward then immediately switching to holding down option until the new message is ready.

**Comment by robertklep** [comment] 2015-12-27 21:01
Haha yeah, I suppose that you can take advantage of the slowness of those animations as well 😀

Thanks for testing, I'll close this issue.

**Closed by robertklep** 2015-12-27 21:01 UTC
